# -*- coding: utf-8 -*-
import sys

f = open("docs/metachat-browser-设计文档.md", "rb")
raw = f.read()
f.close()
text = raw.decode("utf-8-sig").replace("\r\n", "\n")

# Step 3: Update startup params
old_startup = "| 参数 | 类型 | 默认值 | 说明 |\n|------|------|--------|------|\n| --metachat-mode | 开关 | 无 | 启用 MetaChat 模式（隐藏原生 UI） |"
new_startup = "| 参数 | 类型 | 默认值 | 说明 |\n|------|------|--------|------|\n| --metachat-mode | 开关 | 无 | 启用 MetaChat 模式（隐藏原生 UI） |\n| --metachat-mode-allowlist | 字符串 | 空 | 逗号分隔的 IDC 命令 ID，即使在默认拦截列表中也放行 |\n| --metachat-mode-blocklist | 字符串 | 空 | 逗号分隔的 IDC 命令 ID，额外拦截 |\n| --metachat-accounts-config | 路径 | accounts.json | 账号配置文件路径 |\n\n启动示例：\n```bash\nMetaChat.exe --metachat-mode --metachat-accounts-config=C:/Users/xxx/metachat-accounts.json\n```"

if old_startup in text:
    text = text.replace(old_startup, new_startup)
    print("step3 ok")
else:
    print("step3 FAIL - old_startup not found")
    sys.exit(1)

# Step 4: Build new 3.3 section
L = []
def a(s=""):
    L.append(s)

a("### 3.3 核心机制：per-profile 指纹隔离")
a("")
a("#### 3.3.1 背景")
a("")
a("ChromiumFish 的 `fingerprinting::Current()` 是 **进程级单例**，所有 WebContents 共享同一个指纹。")
a("MetaChat 需要**每个账号独立指纹**，不同账号的指纹必须完全隔离（C++ 引擎级别，非 JS 注入）。")
a("")
a("#### 3.3.2 方案：每账号独立 Profile + AppendExtraCommandLineSwitches 注入")
a("")
a("```")
a("browser 进程")
a("  MetaChatAccountStore (管理 accounts.json)")
a("    |- Account A -> user_data_dir=Profile_A, persona_seed=6847...")
a("    |- Account B -> user_data_dir=Profile_B, persona_seed=1928...")
a("    |- Account C -> user_data_dir=Profile_C, persona_seed=8374...")
a("")
a("  ChromeContentBrowserClient::AppendExtraCommandLineSwitches()")
a("    |- child_process_id -> RenderProcessHost::FromID() OK（构造函数已注册）")
a("    |- RPH -> GetBrowserContext() -> GetPath() -> profile 路径")
a("    |- 查 MetaChatAccountStore 拿到 persona_seed")
a("       -> command_line->AppendSwitchASCII(persona-seed, seed)")
a("")
a("renderer 进程 A                renderer 进程 B")
a("  persona-seed=A               persona-seed=B")
a("  DeriveFromSeed               DeriveFromSeed")
a("  -> 指纹 A                    -> 指纹 B")
a("```")
a("")
a("**关键保证：**")
a("")
a("- **不同 profile 的 renderer 进程天然隔离** -- Chromium 不会让不同 BrowserContext 的 WebContents 复用同一 renderer 进程")
a("- **RenderProcessHost::FromID() 在 AppendExtraCommandLineSwitches 调用时已可用** -- RegisterHost() 在构造函数中调用，早于 Init() 中 AppendExtraCommandLineSwitches 的调用")
a("- **Fish 的 kSwitchNames[] 仍保留 kPersonaSeed** -- 作为全局 fallback（Spare RenderProcessHost 等场景）")
a("")
a("#### 3.3.3 补丁修改清单")
a("")
a("| 补丁 | 修改内容 |")
a("|------|---------|")
a("| persona-seed.patch（Fish） | 不修改。保留 kPersonaSeed 在 kSwitchNames[] 中作为 fallback |")
a("| 0004-profile-seed.patch（新） | ChromeContentBrowserClient::AppendExtraCommandLineSwitches() 中通过 child_process_id -> RPH -> BrowserContext -> persona_seed 覆盖注入 |")
a("")
a("#### 3.3.4 accounts.json 格式")
a("")
a("```json")
a('{')
a('  "version": 1,')
a('  "accounts": [')
a('    {')
a('      "id": "wa_work",')
a('      "name": "工作号",')
a('      "platform": "whatsapp",')
a('      "url": "https://web.whatsapp.com",')
a('      "user_data_dir": "Profile_WhatsApp_Work",')
a('      "persona_seed": "684729103847201",')
a('      "proxy": null')
a('    },')
a('    {')
a('      "id": "tg_personal",')
a('      "name": "个人号",')
a('      "platform": "telegram",')
a('      "url": "https://web.telegram.org",')
a('      "user_data_dir": "Profile_Telegram_Personal",')
a('      "persona_seed": "192837465012384",')
a('      "proxy": null')
a('    }')
a('  ]')
a('}')
a("```")
a("")
a("> **MVP 阶段只开放 persona_seed**。用户只需要给不同账号不同 seed，Fish 的 DeriveFromSeed() 自动生成全套一致的指纹（UA、WebGL、音频、Canvas、屏幕等 30+ 维度）。")
a(">")
a("> **Phase 2** 可扩展 persona_overrides 字段，支持精细控制特定维度，同时保持 Fish 默认池的一致性保证。")
a("")
a("#### 3.3.5 后台账号管理")
a("")
a("后台账号的 WebContents 设为 OCCLUDED 状态：")
a("- JS 继续运行（能接收消息）")
a("- 停止渲染/动画")
a("- 释放显存")
a("- 切换到前台时立即恢复全功率")
a("")
a("#### 3.3.6 Phase 2 扩展：persona_overrides")
a("")
a("```json")
a('{')
a('  "accounts": [')
a('    {')
a('      "id": "wa_1",')
a('      "persona_seed": "111",')
a('      "persona_overrides": {')
a('        "os": "mac",')
a('        "screen_width": 2560,')
a('        "screen_height": 1600,')
a('        "hardware_concurrency": 10,')
a('        "webgl_renderer": "Apple M2",')
a('        "timezone": "America/New_York",')
a('        "locale": "en-US"')
a('      }')
a('    }')
a('  ]')
a('}')
a("```")
a("")
a("支持按 **指纹模板** 管理模板库，多账号共享同一模板。")

new_section = "\n".join(L)

start_marker = "### 3.3 核心机制：per-WebContents 指纹"
end_marker = "### 3.4 通用 Overlay 容器"
start_idx = text.index(start_marker)
end_idx = text.index(end_marker)
text = text[:start_idx] + new_section + text[end_idx:]
print("step4: replaced", end_idx - start_idx, "chars with", len(new_section), "chars")

# Write back
text = "\ufeff" + text
text = text.replace("\n", "\r\n")
f = open("docs/metachat-browser-设计文档.md", "wb")
f.write(text.encode("utf-8-sig"))
f.close()
print("write done")
